### ISSUE TITLE
Extension wallets confusing experience - only one is enabled and the rest are disabled

### ISSUE THREAD

**Issue by kazazor** [rsksmart/rLogin#230]
Please see the conversation here: https://open-rsk-dev.slack.com/archives/C02JVHMHC49/p1646837529711779

This is a very serious bug in the eyes of the user.
It will always show you some wallets as disabled even if you have them installed.
We should think about how to resolve it, cause while I may understand some of the tech challenges here - from a UI perspective this has to be resolved.

![image](https://user-images.githubusercontent.com/1577655/157777795-efb8a2cc-e5b1-471a-bbd5-905645c7b90c.png)

**Comment by ilanolkies** [comment]
We need to research if we can fix this. We all agree it is misleading since we implemented first time. Consider all the providers are using `window.ethereum` so all the providers will try to write on the same global.

We need to see if providers write another global that is not `.ethereum` exporting extension operability

**Comment by kazazor** [comment]
Sounds good to me, please update this thread when you have your research results :)

**Comment by jessgusclark** [comment]
We researched this issue and found that since the majority of web providers write the variable `window.ethereum` there is no way to detect which providers the user has installed. The extension that last writes the variable gets priority and is the one the user connects to. In addition, the majority of dapps and tools look for this variable to determine which provider to connect to. 

As such, this is not an issue that rLogin can fix as it exists with browser wallets and dapps.
