### ISSUE TITLE
D'Cent HW - Problem - Sign Message

### ISSUE THREAD

**Issue by mulonemartin** [rsksmart/rLogin#284]
No problem with Ledger or Trezor HW.

![Captura de pantalla de 2022-06-03 08-17-30](https://user-images.githubusercontent.com/793188/171844349-d76444c7-8688-46fe-b450-ae704ee780ab.png)
![Captura de pantalla de 2022-06-03 08-17-43](https://user-images.githubusercontent.com/793188/171844361-568efbe3-cea2-40f4-b81f-253dfaef9d4d.png)
.

**Comment by jessgusclark** [comment]
@mulonemartin Thanks for reporting this bug with the D'Cent provider. I believe I have a fix ready to go but I need some assistance testing it. The bug was in the D'Cent provider package and [my testing is documented in this issue](https://github.com/rsksmart/rLogin-providers/issues/60).

Can you try to install [@rsksmart/rlogin-dcent-provider 1.0.2-beta.6](https://www.npmjs.com/package/@rsksmart/rlogin-dcent-provider) package and let me know if that fixes the issue? I tested it with my device and it worked, I'd like a 2nd pair of eyes on it.

**Comment by jessgusclark** [comment]
I am closing this ticket due to inactivity. I believe the issue has been resolved in the provider package. If there are any additional concerns please reopen or put a new ticket in the providers repo.
