### ISSUE TITLE
Add try again button for unhandled error screens

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rLogin#75]
Ref: https://github.com/rnsdomains/rns-manager-react/issues/390

**Comment by jessgusclark** [comment]
This could be because the localStorage has already cached the `wc` variable and when closing, it tries to connect with the same settings/token. Instead, when this error pops up, remove the localStorage session information.

This could also be an issue with the permissioned app when connecting?

Add retry button if the error is unhandled, not for "Incorrect Network".
