### ISSUE TITLE
Support for Binance

### ISSUE THREAD

**Issue by jacobabiola** [rsksmart/rLogin#91]
I find this product really fascinating and i will like is use it with binance Smart chain. when will you support binance network?

**Comment by jessgusclark** [comment]
Hey Jacob, thanks for the suggestion. I don't know a lot about Binance Smart Chain, but a quick test of the [basic sample app](https://github.com/rsksmart/rlogin-sample-apps), I believe rLogin should work since it is EVM-compatiable. 

**here is what I tested**

1. I setup my Metamaks to connect to the Binance Smart Chain network. [I followed these instructions](https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain).
2. In the [basic sample app](https://github.com/rsksmart/rlogin-sample-apps/tree/main/basic-dapp), I added the chain Id 56 as a supported chain. [See this file, this line](https://github.com/rsksmart/rlogin-sample-apps/blob/main/basic-dapp/src/App.js#L22)

```
const rLogin = new RLogin({
      cacheProvider: false,
      supportedChains: [30, 31, 56]
})
```

3. I was able to log in to the basic app and perform the basic operations. 

![Screen Shot 2021-05-25 at 1 49 26 PM](https://user-images.githubusercontent.com/766679/119485733-17477080-bd60-11eb-842f-61a3d9e84f18.png)

More testing should be done to make sure all operations are supported, but it should work. If you find issues, let me know and if time allows, we can investigate.

Thanks!
